services:
  db:
    image: postgres:15
    platform: linux/amd64
    container_name: smartsewing_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: smartsewing
      POSTGRES_PASSWORD: smartsewing_password
      POSTGRES_DB: smartsewing
    ports:
      - "5432:5432"
    volumes:
      - smartsewing_pgdata:/var/lib/postgresql/data

volumes:
  smartsewing_pgdata:
